### ISSUE TITLE
Feature Request: Remember window proportions and placement

### ISSUE THREAD

**Issue by hyph3n** [Reverp/Toxy#32]
Would it be possible to have Toxy remember its proportions and placement so that it opens that way every time I start the program? Currently, it seems to be returning to a default on every start of the application.

Thanks!

**Comment by Impyy** [comment]
I don't think saving the placement is a good idea. What if the user somehow managed to drag the window to some place where the window is invisible or unreachable?

Saving the proportions would be neat though, I'll add that for sure.

**Comment by hyph3n** [comment]
There are usually little tricks you can use to bring a "lost" window back onto your desktop if you've disconnected a secondary display or something (I've had to use them before for other programs). That said, saving the proportions is the big one for me. I can deal with moving the window around on screen a bit. Thanks for the quick response.

**Comment by Impyy** [comment]
With proportions, do you also mean the friend column width and such? Or just the window width and height?

**Comment by hyph3n** [comment]
Width and height are the most important to me, but I can see how adjusting the friend column could be useful to some people.

**Comment by Impyy** [comment]
Commit https://github.com/Reverp/Toxy/commit/0b901e0d0d0f82c38059cae9824537edfbfe1d0a addresses this. 

Thanks for your suggestions!
