### ISSUE TITLE
Feature Request: Gravatar Avatars

### ISSUE THREAD

**Issue by kevinkjt2000** [Reverp/Toxy#34]
http://gravatar.com/
Please?

**Comment by hypereddie** [comment]
Aren't gravatar's linked to emails?

As far as I know, Toxy doesn't use emails..so wouldn't there need to be a system of confirming the user's email?

**Comment by Impyy** [comment]
Tox clients are not supposed to interact with anything except for the tox network itself and services defined in the [STS](https://github.com/Tox/Tox-STS/blob/master/STS.md). This is what every tox user takes for granted so we can't just add things like this.

**Comment by kevinkjt2000** [comment]
I had not read the STS yet.  Thanks for sharing the link.
