### ISSUE TITLE
Feature req: Show build version

### ISSUE THREAD

**Issue by drdaffey** [Reverp/Toxy#43]
It would be really good to have an idea of the build version or at least the build date somewhere in the app.

I've yet to understand how the Updater functions and is it bound to the actual app, but a date at the end of the Settings tab, for example, would be really informative.

**Comment by Impyy** [comment]
The updater isn't finished and doesn't do much yet. Basically what'll happen in the future is: you start Toxy through the updater. The updater checks if there's a new version, if so, it updates the files. After that process is done, it'll start Toxy. The current plan is the start versioning Toxy once toxcore does so too (which should be soon) or perhaps even sooner if that ends up taking too long.

Anyways, yes, I think it's a good idea to include the build number and build date. The only problem is that the build numbers of x86 and x64 builds on jenkins don't correspond to each other, which might cause confusion. (the latest x86 build is 386 and the latest x64 build is 251)

I think I'll just add the following info to the settings tab:
- Platform target
- Build number
- Build date

**Comment by drdaffey** [comment]
I think that'd be grand. So, let me get this straight, does the updater download updates now?

**Comment by Impyy** [comment]
Well if you pass "/nightly" to it it'll download, extract and verify the signature of the latest nightly build for the platform you're on. Actually using it for anything else isn't useful/safe just yet ;)

**Comment by Impyy** [comment]
https://github.com/Reverp/Toxy/commit/36527d19402e6b844c7c651e13f3d75b677f0d2f
