### ISSUE TITLE
Randomize Nospam button

### ISSUE THREAD

**Issue by drdaffey** [Reverp/Toxy#44]
Nospam textbox is way too large, the button gets overlapped by the scrollbar. Shorten the textbox so that the button's right side aligns with the top and bottom controls' sides.

**Comment by Impyy** [comment]
https://github.com/Reverp/Toxy/commit/9e7ac023452674920a7b352ae41f77ba11b2c84c
Is this better?

**Comment by drdaffey** [comment]
Absolutely what I had in mind. Thank you.
