### ISSUE TITLE
FilterAudio

### ISSUE THREAD

**Issue by TimBo93** [Reverp/Toxy#46]
filterAudio.EchoFilterEnabled = false;

doesn't work because that field is not existing.

**Comment by Impyy** [comment]
Did you update your SharpTox.Av.Filter recently? (and filter_audio)
https://github.com/Impyy/SharpTox.Av.Filter/commit/282a9bb559c4aa95bf5275a453af156201841d46

**Comment by TimBo93** [comment]
oh sorry :+1: i copied the dlls from the updater into the lib folder. And that didn't work. But a rebuild of Av.Filter worked.
