### ISSUE TITLE
Translating Toxy

### ISSUE THREAD

**Issue by maxkorsov** [Reverp/Toxy#62]
Hi!

Like Toxy, and I would like to help with translation into Russian.
I think you will have in the near future a lot of wishing to translations into other languages.

Prompt me, how can I give you a file with translation into Russian language. (<b>Ru.xaml</b>). I am ready to send you by e-mail or other means.

**Comment by TimBo93** [comment]
you can commit the translated xaml version direct into git.
Another alternative is to paste your translation here : https://piratenpad.de/p/Russian_Translation_for_Toxy

I will add the c# code to load your language resource.

Greets,
TimBo

**Comment by maxkorsov** [comment]
Awesome!
I did as you said.
How to me the next time send changes?

**Comment by TimBo93** [comment]
here it is
https://github.com/Reverp/Toxy/pull/63
thank you very much !

if that pull-request is accepted, you can edit the xaml file with git.

Just fork that Toxy Repo into your github account
Clone that fork inside your computer
Make Changes
Commit & Push your changes into your github-fork
Create a pull-request.
